name: glade_two
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/


  fonts:
     - family: DMSans
       fonts:
         - asset: assets/fonts/DMSans-Bold.ttf
         - asset: assets/fonts/DMSans-Medium.ttf
         - asset: assets/fonts/DMSans-Regular.ttf
           weight: 700
     - family: DMSMedium
       fonts:
         - asset: assets/fonts/DMSans-Medium.ttf
           weight: 700

     - family: DMSRegular
       fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 700
     - family: DMSRegular
       fonts:
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
